[theme]
base = "light"
primaryColor = "#007E0E"        # Bright Green
backgroundColor = "#FFFFFF"   # White background
secondaryBackgroundColor = "#F0F2F6"  # Light gray cards/sidebars
textColor = "#000000"         # Black text
font = "sans serif"


[server]
runOnSave = true

[ui]
hide_sidebar_nav = true  # ✅ This hides the built-in page list
