[GOOGLE_CREDENTIALS]
type = "service_account"
project_id = "alpha-landas"
private_key_id = "265a2b1e32b8b1c99b2f93e6e059471a15c0a8c2"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCmA96spfFb9KaL
3U8R3OT8HSSP0D9xZY8pH0VsrN6vABgPaeuK0CBtt+ywV31+oqZO4RNdF0Acbnjw
9TfKj3ZK5kZXZlF8aCNBrIcyMpKIdGztHVAaC0w5MoxT5edjJZX+tzLGm9PK4QFl
OOdZ6fzOlg/YEYdEb1wMGrcS72b4XBaWsPp7BUJVrLVAcF0gii/xNPwXf9od+Tyo
lAVnRpIR5KBjtV2lEAYAjEkFDa1U6LDjpf6stI5rX5Qf1y75DR4i8fVjSSx3DOQJ
1mIdnnts+NhRBoblOj3STyo9kUc/VHFzt8uQSrelYqsQY/gkvO7ws1UWn8gEt2ll
KG/HaD7nAgMBAAECggEAD6rj0/VhPuVq5l4/fRcUwTpa3fuwURpdlWrvGV+DMI7Y
tnOvmA0mUlR+UPIg1NeyzFTvh+SO12ARp+PsnQBHELCEyPDOFeiaEzOeGr2tGJWs
RgBzM9IHIorDtZNH8BJ3Am/1qcrBBS+Q+yWQp+quQizlV+XnlyzPShEnX/EaDawz
96qIZ8lTpw4iJuMkg+CFnnEGjALv6Doneie9MOoDwnYk9km8/2t9UjkYkV5UF4bk
QR5tr5n6XC3tSVox5/KoC89GguBmu7hENsU7LPM94auWSVNzxg2meAs3Oy43kd/I
zSuBxhGuS8qiWBmEkaiB5RYlafSUNoqfKYF3CwrieQKBgQDqEI/XUYnxH3j1tX4Y
EQYv1hjqpvtt617UCTCnozjjSyivH6h8NIizMUPXgRDVg45rR64yXRhrE+9DTt56
qnOb85MdN5e8kKSk4wZyOWukvFeInwp5KQZYccnZUd8wk7ZsbvAws+RUic/6X0lM
zTvkNBwJZhXhXVwOOLPrm4mxcwKBgQC1kruahNdvKaDYSxwugIKSlpeT5pWPyWLV
YklxBtlg8UmaveqOXMPjcJsRQ3bX0uJ/OW4u0awy+wsYwxX06WBubCjmPLVNdUl/
DpSV3BGb601qJbkfA/TLmnr/nQkE08rxEgMLQOsnEm25EE7Vwn7Isb64Vdo7n5UR
FFcGCJuPvQKBgQDkItJgVswxZbCbJJPLV0SFeZL9m1WzNFdQKcjvi+qVt5rm3d91
eCrJJTpvoQ/MXBaDP/Fsi0qSi3KIUyYLv3lBRq5cKuRNWVnwkIqm6IqfnSdgNUua
/j5+FCJeHCuDCGYk2BhqD9x7/XrmGNuz7NH0QkoVaxfmef2QqvnKqeYSOwKBgENH
p7RN3PYX2r3KtxqUC839dxUar/ijire+v6/d9dZyEfAAx1UREpTIOO1grjyyq7Kw
uR8oGkKZuzblstEZWN4RveXyQMv+1cj6whv1e6Dmw7y9VackdCStjT4CFkFvqRdC
sVYOLBRCQ937KPsUIp6DHkR3q3HEZBv8CXL25Y2RAoGAIfbwg4yTG8/WdOk30YZJ
CsvlWOkmD54GoPuUk4UfI0BtM8bl+lEEK5F6ldYes9Fx3TroAHCdi3ogZeExLPpf
Y+rpWaDw7dXU0jp0L+8ThBP6+qMi6//LNZNn5NYQjFla8Zy1COKvvlBg6aWYC400
Fzg3JBjswrEdI/9syHCXwbA=
-----END PRIVATE KEY-----"""
client_email = "landas-service-account@alpha-landas.iam.gserviceaccount.com"
client_id = "113333711694702374021"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/landas-service-account%40alpha-landas.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
